import test from 'node:test';
import assert from 'node:assert/strict';
import {createCareer,emptyBat,emptyPitch,qualification,ranking,money,overall,rosterPlan,negotiateSalary,salaryOffer,visibleSalaryChange,acknowledgeEvent,optionRule,settleOptions,progress,offers,faGrade,secondaryDraftEligible,secondaryDraft,releasedSecondaryDraft,excludeFromReserve,freeAgentOffers,freeAgentTryout,nationalEvents,waiverCheck,advanceWaiverYear,saveCareer,loadCareer,enlist} from '../src/engine.js';

const base={name:'검증',school:'검증고',role:'bat',position:'중견수',type:'교타형',team:0,seed:91};
const pro=seed=>{const c=createCareer({...base,seed});c.stage='프로';c.phase='prepare';c.age=25;c.proYears=4;c.reserved=true;c.playerStatus='reserved';c.contract={kind:'reserved',annualMan:6000,left:0};return c;};

test('규정타석은 버림, 규정이닝은 팀 경기 수',()=>{assert.equal(qualification(144,'bat'),446);assert.equal(qualification(80,'bat'),248);assert.equal(qualification(144,'pitch'),432);assert.equal(qualification(80,'pitch'),240);const b={id:'b',role:'bat',team:0,stat:{...emptyBat(),g:100,pa:446,ab:400,h:120}},p={id:'p',role:'pitch',team:1,stat:{...emptyPitch(),g:30,outs:432,er:60}};const s={games:144,teams:[{id:0,g:144},{id:1,g:144}],players:[b,p]};assert.equal(ranking(s,'bat','avg',true).length,1);assert.equal(ranking(s,'pitch','whip',true).length,1);b.stat.pa=445;p.stat.outs=431;assert.equal(ranking(s,'bat','avg',true).length,0);assert.equal(ranking(s,'pitch','whip',true).length,0);});
test('팀 경기 수가 다르면 선수별 자격도 달라진다',()=>{const a={id:'a',role:'bat',team:0,stat:{...emptyBat(),g:70,pa:300,ab:250,h:90}},b={id:'b',role:'bat',team:1,stat:{...emptyBat(),g:70,pa:300,ab:250,h:90}};const s={games:144,teams:[{id:0,g:90},{id:1,g:144}],players:[a,b]};assert.deepEqual(ranking(s,'bat','avg',true).map(x=>x.id),['a']);});
test('오버롤은 역할과 포지션 가중치가 다르다',()=>{const p={role:'pitch',position:'선발',a:[50,60,60,90,60,50]};const starter=overall(p);p.position='마무리';assert.ok(starter>overall(p));const b={role:'bat',position:'1루수',a:[50,80,60,50,90,80]};const corner=overall(b);b.position='포수';assert.ok(overall(b)>corner);});
test('1군 주전은 날짜별 1군 등록 기록에서 계산된다',()=>{const c=pro(1);c.player.a.fill(90);const plan=rosterPlan(c);assert.equal(plan.tier,3);assert.equal(plan.registeredDays,plan.calendar.filter(x=>x==='1군').length);assert.equal(plan.minorDays.filter(Boolean).length,0);});
test('재협상은 인라인 결과로 저장되고 표시 금액 기준 변화율을 쓴다',()=>{const c=pro(2);c.salaryPending=true;const base=salaryOffer(c),result=negotiateSalary(c,true);assert.equal(result.annualMan,result.accepted?c.contract.annualMan:result.oldMan);const change=visibleSalaryChange(result.oldMan,result.annualMan);assert.equal(result.raisePercent,change.kind==='삭감'?-change.rate:change.rate);assert.equal(c.pendingEvent,null);assert.equal(c.salaryDecision,result);assert.equal(c.contractHistory.at(-1).annualMan,result.annualMan);assert.equal(money(269800),'27.0억');});
test('연봉협상 결과가 새로고침 뒤에도 팝업 없이 복구된다',()=>{const c=pro(12);c.salaryPending=true;negotiateSalary(c,true);let json;saveCareer(c,{setItem:(_,value)=>json=value});const restored=loadCareer({getItem:()=>json});assert.deepEqual(restored.salaryDecision,c.salaryDecision);assert.equal(restored.pendingEvent,null);assert.equal(restored.phase,'prepare');});
test('성과 옵션은 달성한 경우에만 지급된다',()=>{for(const [role,pos,key] of [['bat','중견수','g'],['pitch','선발','w'],['pitch','중간계투','hold'],['pitch','마무리','sv']]){const rule=optionRule(role,pos,5000),stat={...emptyBat(),...emptyPitch()};stat[key]=rule.target-1;if(pos==='선발')stat.gs=10;assert.equal(settleOptions({options:[rule]},stat)[0].paidMan,0);stat[key]++;assert.equal(settleOptions({options:[rule]},stat)[0].paidMan,5000);}});
test('시즌 종료가 옵션 지급액을 연봉 이력과 시즌 기록에 반영한다',()=>{const c=pro(29);c.player.a.fill(90);c.contract={kind:'fa',left:2,annualMan:10000,options:[{key:'g',target:1,amountMan:3000,label:'1경기 이상'},{key:'g',target:1000,amountMan:7000,label:'1000경기 이상'}]};const row=progress(c);assert.equal(row.optionResults[0].paidMan,3000);assert.equal(row.optionResults[1].paidMan,0);assert.equal(c.salaryLedger.at(-1).optionPaidMan,3000);assert.equal(c.salaryLedger.at(-1).salaryMan,10000);});
test('FA 등급은 선수 연봉에 따라 산정하고 제안별로 바뀌지 않는다',()=>{const c=pro(3);c.phase='market';c.faDeclared=true;c.contract.annualMan=500000;c.salaryLedger=[{salaryMan:500000},{salaryMan:500000},{salaryMan:500000}];const g=faGrade(c);assert.equal(g,'A');assert.ok(offers(c).every(o=>o.grade===g&&o.options[0].amountMan*o.years===o.optionMan));});
test('2차 드래프트는 보류 선수만 대상이고 이동할 때만 이벤트가 뜬다',()=>{const c=pro(4);c.year=2030;c.player.a.fill(50);assert.equal(secondaryDraftEligible(c),true);c.phase='secondary_wait';const result=secondaryDraft(c);assert.equal(result.type,'secondary');assert.equal(!!c.pendingEvent,result.selected);const released=pro(5);released.year=2030;released.player.a.fill(50);excludeFromReserve(released);assert.equal(secondaryDraftEligible(released),false);assert.throws(()=>secondaryDraft(released));assert.equal(released.phase,'release_choice');});
test('보류 제외 후 2차 드래프트 미지명 선수는 입단 테스트를 선택한다',()=>{let c;for(let seed=1;seed<50;seed++){const candidate=pro(seed);excludeFromReserve(candidate);acknowledgeEvent(candidate);if(!releasedSecondaryDraft(candidate).selected){c=candidate;break;}}assert.ok(c);assert.equal(c.phase,'free_tryout_choice');const result=freeAgentTryout(c);assert.equal(result.type,'tryout');assert.equal(c.transactionHistory.at(-1).type,'tryout');});
test('국가대표 시즌과 병역특례가 기록된다',()=>{const c=pro(11);c.year=2030;c.player.a.fill(100);const stat={...emptyBat(),g:140,pa:600,ab:520,h:190,hr:25,bb:65};const events=nationalEvents(c,null,stat);assert.deepEqual(events.map(x=>x.name),['WBC','아시안게임']);assert.equal(c.nationalHistory.length,2);assert.equal(c.exempt,events.some(x=>x.exemption));if(c.exempt)assert.equal(c.served,true);});
test('상무 나이 초과 미필은 입대 필수, 면제자는 시즌 진행 가능',()=>{const c=pro(14);c.age=28;assert.throws(()=>progress(c),/현역 입대/);enlist(c,'regular');assert.equal(c.service,2);const exempt=pro(14);exempt.age=28;exempt.exempt=true;exempt.served=true;assert.doesNotThrow(()=>progress(exempt));});
test('정규시즌 첫 경기 전 웨이버 미영입은 당해 시즌 계약 불가, 다음 해에 자유계약',()=>{let c;for(let seed=1;seed<1000;seed++){const candidate=pro(seed);candidate.phase='season';candidate.player.a.fill(35);if(waiverCheck(candidate)&&candidate.phase==='waiver_wait'){c=candidate;break;}}assert.ok(c);assert.equal(c.pendingEvent.type,'waiver');assert.equal(c.pendingEvent.gameDay,1);assert.deepEqual(freeAgentOffers(c),[]);acknowledgeEvent(c);const year=c.year;advanceWaiverYear(c);assert.equal(c.year,year+1);assert.equal(c.phase,'free_agent');});
test('타자·선발·중간계투·마무리 여러 시드의 시즌 기록',()=>{for(const [role,position] of [['bat','중견수'],['pitch','선발'],['pitch','중간계투'],['pitch','마무리']])for(const seed of [5,17,39]){const c=pro(seed);c.player.role=role;c.player.position=position;c.player.a.fill(76);const row=progress(c);assert.ok(row.stat.g>0);assert.equal(row.minorStat.g,0);assert.ok(Number.isFinite(row.overall));assert.ok(row.awards.every(x=>row.league.awards.some(a=>a.title===x)));if(position==='마무리')assert.equal(row.stat.hold,0);if(position==='선발')assert.equal(row.stat.sv,0);}});
