import test from 'node:test';
import assert from 'node:assert/strict';
import {SAVE_KEY,LEGACY_SAVE_KEYS} from '../src/engine.js';
import {simulateSeason,emptyBat,emptyPitch,rates,ranking,awards,TITLES,sumStats,createCareer,progress,nextYear,resolvePositionOffer,sign,offers,convert,saveCareer,loadCareer,runDraft,finishDraft,developmentalTryout,enterCollege,enlist,injuryForecast,faStatus,declareFA,deferFA,trainingPlan,rosterPlan,collegeEarlyStatus,draftAssessment,sangmuRecruitment,conversionOffer,percentile,percentileReport,totalSalary,money,retire,migrateCareer,positionOffer,changePosition,negotiateSalary,requestTrade,acknowledgeEvent,decideRetirementAdvice} from '../src/engine.js';
const config={name:'검증 선수',school:'테스트고',role:'bat',position:'중견수',type:'교타형',team:0,seed:12345,hand:'우투우타'};
const season=simulateSeason({seed:12345,year:2027});
test('새 저장 키는 이전 키의 커리어를 읽고 새 키에 기록한다',()=>{
  const career=createCareer(config),data=new Map([[LEGACY_SAVE_KEYS[0],JSON.stringify(career)]]);
  const storage={getItem:key=>data.get(key)||null,setItem:(key,value)=>data.set(key,value)};
  assert.deepEqual(loadCareer(storage),career);
  saveCareer(career,storage);
  assert.equal(JSON.parse(data.get(SAVE_KEY)).player.name,career.player.name);
});
test('파생 지표를 원기록에서 정확히 계산',()=>{let b={...emptyBat(),ab:400,h:120,d:20,t:2,hr:18,bb:50,sf:5,pa:455};assert.deepEqual(rates(b,'bat'),{avg:.3,obp:170/455,slg:198/400,ops:170/455+198/400});let p={...emptyPitch(),outs:301,er:35,h:85,bb:25};assert.equal(rates(p,'pitch').era,945/301);assert.equal(rates(p,'pitch').whip,330/301);});
test('리그 전체 투타·승패·득실점 합계와 144경기가 일치',()=>{let b=sumStats(season.players.filter(p=>p.role==='bat').map(p=>p.stat),'bat'),p=sumStats(season.players.filter(p=>p.role==='pitch').map(p=>p.stat),'pitch');assert.equal(b.h,p.h);assert.equal(b.hr,p.hr);assert.equal(b.bb,p.bb);assert.equal(b.k,p.k);assert.equal(b.r,p.r);assert.equal(b.ab-b.h+b.sf-b.e+b.cs,p.outs);assert.equal(b.pa,b.ab+b.bb+b.sf+b.hbp);assert.equal(b.sba,b.sb+b.cs);assert.ok(p.outs>=144*5*48&&p.outs<=144*5*72);assert.equal(p.w,p.l);assert.equal(p.w,season.teams.reduce((a,t)=>a+t.w,0));assert.equal(p.r,season.teams.reduce((a,t)=>a+t.r,0));for(let t of season.teams){assert.equal(t.g,144);assert.equal(t.w+t.l+t.tie,144);}for(let player of season.players){let s=player.stat;assert.ok(s.g<=144);if(player.role==='bat'){assert.ok(s.hr+s.d+s.t<=s.h);assert.ok(s.h<=s.ab);}else{assert.ok(s.gs<=s.g);assert.ok(s.w+s.l+s.sv+s.hold<=s.g);}}});
test('모든 타이틀은 확정 기록의 최고 원값과 일치',()=>{for(let [title,role,key,q] of TITLES){let r=ranking(season,role,key,q),a=season.awards.find(x=>x.title===title);assert.deepEqual(a.winners,r.filter(p=>p.value===r[0]?.value).map(p=>p.id));}});
test('다승 공동 수상과 비율 자격 미달',()=>{let players=[{id:'a',name:'A',role:'pitch',position:'선발',team:0,rookie:true,a:[50,50,50,50,50,50],stat:{...emptyPitch(),g:30,w:20,outs:500,er:60}},{id:'b',name:'B',role:'pitch',position:'선발',team:0,a:[50,50,50,50,50,50],stat:{...emptyPitch(),g:30,w:20,outs:500,er:50}},{id:'c',name:'C',role:'pitch',position:'마무리',team:0,a:[50,50,50,50,50,50],stat:{...emptyPitch(),g:1,w:1,outs:3,er:0}}];let s={players,games:144,teams:[{id:0,w:80}]};assert.deepEqual(awards(s).find(a=>a.title==='다승왕').winners,['a','b']);assert.deepEqual(awards(s).find(a=>a.title==='평균자책점왕').winners,['b']);});
test('같은 시드는 완전히 같은 결과',()=>assert.deepEqual(season,simulateSeason({seed:12345,year:2027})));
test('결장과 출장 기회가 기록을 줄임',()=>{let player={...config,a:[60,60,60,60,60,60]};let full=simulateSeason({seed:12,year:2028,player:{...player,opportunity:1}}).players.find(p=>p.id==='user');let injured=simulateSeason({seed:12,year:2028,player:{...player,opportunity:1,missed:80}}).players.find(p=>p.id==='user');assert.equal(full.stat.g,144);assert.equal(injured.stat.g,64);});
test('선발 체력에 따라 이닝이 달라지고 고정 이닝으로 묶이지 않음',()=>{let low=simulateSeason({seed:88,year:2028,player:{...config,role:'pitch',position:'선발',a:[75,75,75,20,75,75],opportunity:1}}).players.find(p=>p.id==='user').stat;let high=simulateSeason({seed:88,year:2028,player:{...config,role:'pitch',position:'선발',a:[75,75,75,85,75,75],opportunity:1}}).players.find(p=>p.id==='user').stat;assert.ok(low.outs/Math.max(1,low.gs)<high.outs/Math.max(1,high.gs));assert.notEqual(low.outs,low.gs*12);assert.ok(low.w<=low.gs);});
test('마무리 보직은 선발·홀드와 분리되고 불펜 출전은 제한됨',()=>{let s=simulateSeason({seed:91,year:2028,player:{...config,role:'pitch',position:'마무리',a:[85,85,85,50,85,70],opportunity:1}});let p=s.players.find(p=>p.id==='user');assert.equal(p.stat.gs,0);assert.equal(p.stat.hold,0);assert.ok(p.stat.g<=72);assert.ok(p.stat.sv>0);});
function pro(seed=12345){const c=createCareer({...config,seed});c.stage='프로';c.phase='prepare';c.age=22;c.contract={kind:'reserved',annualMan:3300,years:1,left:1,totalMan:3300};c.reserved=true;return c;}
function historyDays(days,start=2020){return days.map((registeredDays,i)=>({year:start+i,stage:'프로',registeredDays,military:false}));}
test('훈련은 경험치 성장량의 배분을 바꾸고 경기 기록은 보존한다',()=>{for(const a of [[0],[1,3]])assert.equal(trainingPlan(a).selected.length,a.length);for(const a of [[],[0,0],[0,1,2],[0,1,2,3],['0'],[6]])assert.throws(()=>trainingPlan(a));let a=createCareer(config),b=structuredClone(a);progress(a,[0]);progress(b,[0,1]);assert.ok(a.player.a[0]>b.player.a[0]);assert.equal(a.history[0].totalGrowth,b.history[0].totalGrowth);assert.deepEqual(a.history[0].stat,b.history[0].stat);});
test('드래프트 단일 지명 · 응원 구단 무관 · 미지명 존재 · FA 외 제안 없음',()=>{let selected=0,missed=0;for(let seed=1;seed<=50;seed++){const a=createCareer({...config,seed}),b=structuredClone(a);a.phase=b.phase='path';b.player.team=7;let x=runDraft(a),y=runDraft(b);assert.deepEqual(x,y);assert.deepEqual(offers(a),[]);assert.throws(()=>sign(a,{team:1,totalMan:3300}));assert.throws(()=>runDraft(a));if(x.selected){selected++;assert.equal(a.player.team,x.team);assert.equal(a.reserved,true);assert.ok(x.round>=1&&x.round<=11);}else missed++;finishDraft(a);assert.equal(a.phase,x.selected?'prepare':'path');}assert.ok(selected&&missed);});
test('고교 성적이 좋을수록 지명 확률과 예상 순위 개선',()=>{let a=createCareer(config),b=structuredClone(a);for(const c of [a,b])c.history=[{stage:'고교',role:'bat',stat:{...emptyBat(),g:36,pa:150,ab:130,bb:20}}];Object.assign(a.history[0].stat,{h:60,hr:14,d:10});Object.assign(b.history[0].stat,{h:15,hr:0,d:1});assert.ok(draftAssessment(a).probability>draftAssessment(b).probability);assert.ok(draftAssessment(a).roundLow<draftAssessment(b).roundLow);});
test('대학 2학년 성적 우수자 조기 진출 · 1학년 불가 · 4시즌 졸업',()=>{let c=createCareer(config);c.phase='path';enterCollege(c);c.player.a.fill(90);c.history=[{stage:'대학',role:'bat',stat:{...emptyBat(),g:36,pa:160,ab:130,h:65,hr:15,bb:30}}];c.collegeSeasons=1;assert.equal(collegeEarlyStatus(c).eligible,false);assert.throws(()=>runDraft(c,'early'));c.collegeSeasons=2;assert.equal(collegeEarlyStatus(c).eligible,true);runDraft(c,'early');assert.equal(c.collegeGraduate,false);let d=createCareer(config);d.phase='path';enterCollege(d);d.collegeSeasons=4;d.phase='result';nextYear(d);assert.equal(d.phase,'draft');assert.equal(d.collegeGraduate,true);assert.equal(faStatus(d).required,7);});
test('FA 등록일 145일 · 미달 합산 · 8/7/재취득4년 · 다년 계약 제한',()=>{let c=pro();c.history=historyDays([145,188,145,145,145,145,72,73]);assert.equal(faStatus(c).seasons,7);assert.equal(faStatus(c).eligible,false);c.collegeGraduate=true;assert.equal(faStatus(c).eligible,true);c.collegeGraduate=false;c.history.push(...historyDays([145],2028));assert.equal(faStatus(c).eligible,true);c.contract={kind:'fa',left:1};assert.equal(faStatus(c).eligible,false);c.contract.left=0;c.faCount=1;c.faCycleStart=2025;assert.equal(faStatus(c).required,4);assert.equal(faStatus(c).seasons,3);});
test('연봉 조정은 잔류 · 선언 전 복수 제안 차단 · FA 선언과 계약',()=>{let c=pro();progress(c);while(c.pendingEvent)acknowledgeEvent(c);let team=c.player.team;nextYear(c);assert.equal(c.phase,'prepare');assert.equal(c.player.team,team);assert.deepEqual(offers(c),[]);assert.throws(()=>declareFA(c));c.history.push(...historyDays(Array(8).fill(145)).map(x=>({...structuredClone(c.history[0]),...x})));c.phase='fa_choice';deferFA(c);assert.equal(c.phase,'prepare');assert.equal(faStatus(c).eligible,true);c.phase='fa_choice';declareFA(c);let o=offers(c);assert.equal(o.length,3);sign(c,o[1]);assert.equal(c.player.team,o[1].team);assert.equal(c.contract.left,o[1].years);assert.equal(c.faCount,1);assert.equal(faStatus(c).eligible,false);assert.deepEqual(offers(c),[]);});
test('2군 기록과 날짜별 등록 상태는 별도로 일치한다',()=>{let c=pro();c.player.a.fill(46);const plan=rosterPlan(c);assert.equal(plan.label,'2군');assert.equal(plan.registeredDays,plan.calendar.filter(x=>x==='1군').length);let row=progress(c);assert.ok(row.minorStat.g>0);assert.equal(row.minorLeague.awards.length,0);assert.equal(row.minorLeague.games,108);assert.equal(row.league.games,144);let h=createCareer(config);progress(h);assert.deepEqual(h.history[0].awards,[]);assert.deepEqual(h.history[0].league.awards,[]);});
test('출전 단계는 네 단계이며 실제 출전으로 결정된다',()=>{assert.deepEqual([40,55,61,80].map(v=>{let c=pro();c.player.a.fill(v);return rosterPlan(c).tier;}),[0,1,2,3]);let c=pro();c.player.a.fill(58);let row=progress(c);assert.ok(['2군','1군 백업','1군 준주전','1군 주전'].includes(row.level));});
test('상무 지원 기회와 선발 경쟁 재현 · 탈락 후 현역 가능',()=>{let rejected=false,accepted=false;for(let seed=1;seed<=100;seed++){let c=pro(seed);c.proYears=1;const s=sangmuRecruitment(c);assert.ok(s.slots>0);let a=structuredClone(c);let ok=enlist(c,'athletic');assert.equal(enlist(a,'athletic'),ok);if(ok)accepted=true;else{rejected=true;assert.equal(c.service,0);assert.equal(sangmuRecruitment(c).alreadyApplied,true);assert.throws(()=>enlist(c,'athletic'));assert.equal(enlist(c,'regular'),true);assert.equal(c.service,2);}}assert.ok(rejected&&accepted);});
test('복무 2시즌 · 상무 2군 기록 · 현역 무출장 · 랜덤 능력 이벤트',()=>{let events=false;for(let seed=1;seed<=8;seed++){let a=pro(seed),b=structuredClone(a);a.service=b.service=2;a.servicePath='athletic';b.servicePath='regular';let ra=progress(a),rb=progress(b);assert.ok(ra.minorStat.g>0);assert.equal(rb.stat.g+rb.minorStat.g,0);assert.equal(a.clubTrust,b.clubTrust);assert.equal(ra.registeredDays,0);assert.deepEqual(ra.awards,[]);assert.equal(totalSalary(a),0);assert.ok(a.allowanceIncome>0);events ||=ra.report.length>0||rb.report.length>0;while(b.pendingEvent)acknowledgeEvent(b);nextYear(b);progress(b);while(b.pendingEvent)acknowledgeEvent(b);nextYear(b);assert.equal(b.served,true);assert.equal(b.age,24);}assert.ok(events);});
test('전향은 3시즌 극심한 부진에서만 · 과거 기록 보존',()=>{let c=pro();c.age=25;assert.equal(conversionOffer(c),null);assert.throws(()=>convert(c));const row={stage:'프로',role:'bat',military:false,stat:{...emptyBat(),g:50,pa:100,ab:100,h:10},minorStat:emptyBat()};c.history=[structuredClone(row),structuredClone(row)];assert.equal(conversionOffer(c),null);c.history.push(structuredClone(row));assert.ok(conversionOffer(c));let old=structuredClone(c.history);convert(c);assert.equal(c.player.role,'pitch');assert.equal(c.adapt,2);assert.deepEqual(c.history,old);assert.equal(conversionOffer(c),null);let normal=pro();normal.age=25;normal.history=structuredClone(old);normal.history[2].stat.h=50;assert.equal(conversionOffer(normal),null);});
test('백분위 동률 중간순위 · 역방향 지표 · 표본 미달',()=>{assert.equal(percentile(3,[1,2,3]),100);assert.equal(percentile(1,[1,2,3],true),100);assert.equal(percentile(2,[1,2,2,3]),50);assert.equal(percentile(2,[2,2,2]),50);let s=simulateSeason({seed:7,year:2028,player:{...config,a:Array(6).fill(75),opportunity:1}});let report=percentileReport(s,'bat');assert.equal(report.length,9);assert.ok(report.every(x=>x.percentile>=0&&x.percentile<=100));s.players.find(x=>x.id==='user').stat.pa=1;assert.ok(percentileReport(s,'bat').every(x=>Number.isFinite(x.percentile)));});
test('안타 백분위는 리그 전체를 네 표본 구간에 포함한다',()=>{let s=simulateSeason({seed:1,year:2028,player:{...config,a:Array(6).fill(60),opportunity:1}}),stat=s.players.find(p=>p.id==='user').stat;stat.pa=500;stat.ab=440;stat.h=109;let hit=percentileReport(s,'bat').find(x=>x.key==='h');assert.equal(hit.threshold,446);assert.equal(hit.count,s.players.filter(p=>p.role==='bat'&&p.stat.pa>=446).length);assert.ok(hit.percentile>=0&&hit.percentile<=100);stat.pa=100;hit=percentileReport(s,'bat').find(x=>x.key==='h');assert.equal(hit.qualification,'25%');assert.equal(hit.count,s.players.filter(p=>p.role==='bat').length);});
test('금액 표기 · 지급 연봉만 집계 · 은퇴 보존',()=>{assert.equal(money(3300),'3300만원');assert.equal(money(23000),'2.3억');assert.equal(money(null),'미기록');let c=pro();progress(c);assert.equal(totalSalary(c),3300);c.signingIncome=20000;retire(c);assert.equal(totalSalary(c),3300);assert.equal(c.history.length,1);assert.throws(()=>progress(c));});
test('재활 선택은 결장과 재발 위험에 반영',()=>{let c;for(let seed=1;seed<100;seed++){const a=pro(seed);if(injuryForecast(a)){c=a;break;}}assert.ok(c);let fast=structuredClone(c);c.rehabChoice='safe';fast.rehabChoice='fast';progress(c);progress(fast);assert.ok(c.history[0].injury.days>fast.history[0].injury.days);assert.ok(c.recurrenceAdjustment<fast.recurrenceAdjustment);});
test('v1 이관 · 과거 기록 보존 · 연봉/2군 누락을 조작하지 않음',()=>{let c=pro();progress(c);let old=structuredClone(c);old.version=1;old.contract={years:1,total:33};delete old.salaryLedger;let migrated=migrateCareer(old);assert.equal(migrated.version,7);assert.equal(migrated.history[0].stat.h,old.history[0].stat.h);assert.equal(migrated.history[0].minorStat,null);assert.equal(migrated.history[0].salaryMan,null);assert.equal(totalSalary(migrated),0);assert.equal(migrated.legacySalaryYears,1);});
test('저장 왕복 · 오류 전달 · 손상된 파일 차단',()=>{let c=pro();progress(c);let raw;const storage={setItem:(_,v)=>raw=v,getItem:()=>raw};saveCareer(c,storage);assert.deepEqual(loadCareer(storage),c);assert.throws(()=>saveCareer(c,{setItem:()=>{throw Error('quota');}}),/quota/);assert.throws(()=>loadCareer({getItem:()=>'{bad'}));assert.throws(()=>loadCareer({getItem:()=>JSON.stringify({...c,version:999})}),/버전/);});
test('기존 v2 저장의 새 필드 누락도 복구한다',()=>{let c=pro();progress(c);c.version=2;for(const key of ['contractHistory','nationalHistory','transactionHistory','pendingEvent','exempt','playerStatus'])delete c[key];const loaded=loadCareer({getItem:()=>JSON.stringify(c)});assert.equal(loaded.version,7);assert.equal(loaded.history[0].stat.h,c.history[0].stat.h);assert.equal(loaded.history[0].defenseUnrecorded,true);assert.deepEqual(loaded.contractHistory,[]);assert.deepEqual(loaded.nationalHistory,[]);assert.deepEqual(loaded.transactionHistory,[]);});
test('고교부터 45세까지 진행 · FA · 군복무 · 저장 용량',()=>{let c=createCareer(config),fa=false;let count=0;while(c.age<45&&!c.retired){assert.ok(count++<160,'진행 상태가 막히지 않음');if(c.pendingEvent){c.pendingEvent=null;continue;}switch(c.phase){case 'season':progress(c,[0,1]);break;case 'prepare':if(c.age===24&&!c.served&&!c.service)enlist(c,'regular');if(c.salaryPending)negotiateSalary(c);if(c.stage==='프로')c.player.a.fill(85);if(c.pendingEvent)c.pendingEvent=null;progress(c,[0,1]);break;case 'result':nextYear(c);break;case 'position_choice':resolvePositionOffer(c,false);break;case 'path':if(c.lastDraft&&!c.lastDraft.selected)developmentalTryout(c);else runDraft(c);break;case 'draft_result':finishDraft(c);break;case 'fa_choice':fa=true;declareFA(c);break;case 'market':sign(c,offers(c)[1]);break;case 'contract_result':c.phase='prepare';break;case 'retirement_advice':decideRetirementAdvice(c,false);break;case 'free_agent':c.phase='prepare';break;default:assert.fail(c.phase);}}if(!c.retired)retire(c);assert.ok(c.history.length>=20);assert.ok(fa);assert.ok(c.history.some(r=>r.military));assert.ok(c.history.every(r=>r.league.year===r.year));const finite=x=>{if(typeof x==='number')assert.ok(Number.isFinite(x));else if(x&&typeof x==='object')Object.values(x).forEach(finite);};finite(c);let raw=JSON.stringify(c);assert.ok(Buffer.byteLength(raw)<5_500_000,`저장 크기 ${Buffer.byteLength(raw)}`);assert.equal(loadCareer({getItem:()=>raw}).retired,true);});
test('육성 입단은 2군에서 시작하고 연봉·트레이드 선택은 저장된다',()=>{let c=pro();c.developmental=true;c.proYears=0;c.player.a.fill(70);assert.ok(rosterPlan(c).tier<=1);c.proYears=2;c.salaryPending=true;let offer=c.contract.annualMan;negotiateSalary(c,true);assert.equal(c.salaryPending,false);assert.ok(c.contract.annualMan>=offer);assert.equal(c.contractHistory.length,1);requestTrade(c);assert.equal(c.tradeRequestYear,c.year);assert.throws(()=>requestTrade(c));let raw;saveCareer(c,{setItem:(_,v)=>raw=v});assert.equal(loadCareer({getItem:()=>raw}).tradeRequestYear,c.year);});
test('우수 FA는 최근 3시즌의 출장과 OPS에 따라 보장액과 옵션이 분리된다',()=>{let c=pro(1);c.phase='market';c.faDeclared=true;c.age=29;c.contract.annualMan=20000;c.history=[0,1,2].map(()=>({stage:'프로',military:false,role:'bat',stat:{...emptyBat(),g:140,pa:600,ab:520,h:185,d:35,hr:25,bb:70,sf:10},league:{teams:[{id:0,w:70}]}}));let strong=offers(c);assert.ok(strong.some(o=>o.totalMan>400000));assert.ok(strong.some(o=>o.guaranteedMan===o.totalMan&&o.optionMan===0)&&strong.some(o=>o.optionMan>0));c.history[0].stat.pa=80;c.history[0].stat.ab=70;c.history[0].stat.h=15;c.history[0].stat.hr=1;c.history[0].stat.d=2;c.history[0].stat.bb=8;c.history[0].stat.sf=2;assert.ok(offers(c)[0].totalMan<strong[0].totalMan);});
test('현역 복무에는 경기와 구단 훈련 성장이 없다',()=>{let c=pro(17);c.service=2;c.servicePath='regular';c.player.a=[50,50,50,50,50,50];let before=[...c.player.a],row=progress(c,[0,1]);assert.equal(row.stat.g+row.minorStat.g,0);assert.ok(c.player.a[0]<=before[0]);assert.ok(c.player.a[1]<=before[1]);assert.ok(c.player.a[2]<=before[2]);});

test('코치 포지션 변경 · 적응과 기회 반영 · 과거 기록 보존',()=>{let c=pro();c.year=2031;c.proYears=2;c.player.a[4]=40;let row=progress(c);c.phase='prepare';const old=structuredClone(c.history),before=rosterPlan(c).score;assert.equal(positionOffer(c).target,'지명타자');changePosition(c);assert.equal(c.player.position,'지명타자');assert.equal(c.adapt,1);assert.ok(rosterPlan(c).score<before,'첫 시즌 적응 페널티');c.adapt=0;assert.ok(rosterPlan(c).score>before,'적응 후 출전 평가 상승');assert.deepEqual(c.history,old);});
test('투수 2군 원기록 보존과 역할별 백분위',()=>{let c=pro(323);c.player.role='pitch';c.player.position='선발';c.player.type='제구형';c.player.a.fill(48);let row=progress(c);assert.ok(row.minorStat.outs>0);assert.equal(row.minorStat.gs,row.minorStat.g);let report=percentileReport(row.minorLeague,'pitch');assert.equal(report.length,8);assert.ok(report.some(x=>x.key==='whip'));assert.ok(report.every(x=>x.percentile===null||Number.isFinite(x.percentile)));});
