import test from 'node:test';
import assert from 'node:assert/strict';
import {createCareer,progress,nextYear,collegeEarlyStatus,runDraft,requestTrade,decideTradeOffer,rosterPlan,visibleSalaryChange,simulateSeason,standings,loadCareer,saveCareer,ranking,qualification} from '../src/engine.js';
const config=(seed=1,role='bat',position='유격수')=>({seed,name:'검증 선수',school:'검증고',role,position,type:role==='bat'?'수비형':'선발형',team:0});
const professional=(seed=1)=>{const c=createCareer(config(seed));c.stage='프로';c.phase='prepare';c.proYears=3;c.age=24;c.contract={kind:'reserved',annualMan:18000,left:0};c.salaryPending=true;return c;};
test('고교 팀 경기와 개인 경기, 선발 등판을 분리하고 대회별 기록 합계가 맞는다',()=>{for(const role of ['bat','pitch'])for(const seed of [1,2,3,4,5]){const c=createCareer(config(seed,role,role==='bat'?'유격수':'선발')),row=progress(c),team=row.league.teams.find(t=>t.id===row.team);assert.ok(team.g>=14);assert.equal(team.g,Object.values(team.competitions).reduce((n,x)=>n+x.g,0));assert.ok(row.stat.g<=team.g);if(role==='pitch'){assert.equal(row.stat.gs,row.stat.g);assert.ok(row.stat.gs<team.g);}else{assert.ok(row.stat.pa>=row.stat.g);assert.equal(row.minorStat.g,0);assert.deepEqual(row.rosterMoves,[]);}}});
test('대학 2학년은 능력과 관계없이 얼리드래프트를 선택하며 미지명도 가능하다',()=>{let selected=0,missed=0;for(let seed=1;seed<=80;seed++){const c=createCareer(config(seed));c.stage='대학';c.phase='prepare';c.collegeSeasons=2;c.player.a.fill(30);assert.equal(collegeEarlyStatus(c).eligible,true);const d=runDraft(c,'early');selected+=+d.selected;missed+=+!d.selected;}assert.ok(selected>0&&missed>0);});
test('실책은 안타와 별개이며 수비 능력과 포지션에 따라 분포가 달라진다',()=>{const strong=[],weak=[];for(let seed=1;seed<=12;seed++){const p=config(seed);p.a=[55,55,55,55,95,95];strong.push(simulateSeason({seed,year:2027,player:p}).players.find(x=>x.id==='user').stat.e);p.a=[55,55,55,55,25,25];weak.push(simulateSeason({seed,year:2027,player:p}).players.find(x=>x.id==='user').stat.e);}assert.ok(weak.reduce((a,b)=>a+b,0)>strong.reduce((a,b)=>a+b,0));});
test('트레이드는 구단이 수락하면 즉시 이적하고 거절하면 신뢰도가 내려간다',()=>{let accepted,declined;for(let seed=1;seed<300&&(!accepted||!declined);seed++){const c=professional(seed),before=c.player.team,event=requestTrade(c);if(event.outcome==='수락'&&!accepted)accepted={c,before,event};else if(event.outcome!=='수락'&&!declined)declined={c,before,event};}assert.ok(accepted&&declined);assert.equal(accepted.c.player.team,accepted.event.newTeam);assert.notEqual(accepted.c.player.team,accepted.before);assert.equal(accepted.c.tradeOffer,undefined);assert.equal(accepted.c.pendingEvent.type,'trade');assert.equal(declined.c.player.team,declined.before);assert.ok(declined.c.clubTrust<70);assert.throws(()=>decideTradeOffer(declined.c,true));});
test('신뢰도는 비슷한 선수의 출장 등급에 영향을 주고 구버전 저장은 이관한다',()=>{const a=professional(12),b=structuredClone(a);a.clubTrust=100;b.clubTrust=20;assert.ok(rosterPlan(a).score>rosterPlan(b).score);assert.ok(rosterPlan(a).tier>rosterPlan(b).tier);const old=structuredClone(a);old.version=3;delete old.clubTrust;delete old.trustHistory;old.condition=87;old.gameSense=62;let raw;saveCareer(a,{setItem:(_,v)=>raw=v});const restored=loadCareer({getItem:()=>raw});assert.equal(restored.clubTrust,100);const migrated=loadCareer({getItem:()=>JSON.stringify(old)});assert.equal(migrated.clubTrust,70);assert.equal('gameSense' in migrated,false);});
test('보이는 연봉 금액과 변경률, 팀 순위와 비율·누적 자격이 일치한다',()=>{assert.deepEqual(visibleSalaryChange(12000,12310),{old:12000,new:12000,rate:0,kind:'동결'});assert.equal(visibleSalaryChange(12000,13000).kind,'인상');assert.equal(visibleSalaryChange(12000,11000).kind,'삭감');const league=simulateSeason({seed:7,year:2027});const ranked=standings(league);assert.equal(ranked.length,10);for(const t of ranked)assert.equal(t.rank,1+ranked.filter(x=>x.pct>t.pct).length);assert.equal(qualification(144,'bat'),446);const low=league.players.find(p=>p.role==='bat');low.stat.pa=1;assert.equal(ranking(league,'bat','avg',true).some(p=>p.id===low.id),false);assert.equal(ranking(league,'bat','h',false).some(p=>p.id===low.id),true);});
test('재협상 성공은 소수이고 낮은 연봉과 높은 연봉의 부진 대응이 다르다',async()=>{const {negotiateSalary,salaryOffer,emptyBat}=await import('../src/engine.js');let wins=0;for(let seed=1;seed<=200;seed++){const c=professional(seed);const result=negotiateSalary(c,true);wins+=+result.accepted;}assert.ok(wins>10&&wins<80,`200회 중 ${wins}회 성공`);const bad={year:2029,stage:'프로',military:false,role:'bat',position:'유격수',stat:{...emptyBat(),g:100,pa:420,ab:380,h:45,hr:1,bb:20}};const low=professional(7);low.contract.annualMan=4000;low.history=[bad,bad,bad];const high=structuredClone(low);high.contract.annualMan=50000;assert.ok(salaryOffer(low)>=3900);assert.ok(salaryOffer(high)<50000);assert.ok((50000-salaryOffer(high))/50000>(4000-salaryOffer(low))/4000);});

test('포지션별 수비 부담이 실책 분포에 반영된다',()=>{let corner=0,first=0;for(let seed=31;seed<=42;seed++){for(const [position,add] of [['3루수',n=>corner+=n],['1루수',n=>first+=n]]){const player=config(seed,'bat',position);player.a=[60,60,60,60,50,50];const row=simulateSeason({seed,year:2027,player}).players.find(x=>x.id==='user').stat;add(row.e);}}assert.ok(corner>first,`3루 ${corner}, 1루 ${first}`);});
